version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: account-db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
