spring:
  application:
    name: griisa-account-service

  datasource:
    url: jdbc:postgresql://localhost:5433/accountdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    initialize-schema: always
    jdbc:
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework: INFO
      com.example.griisa_account_service: DEBUG

kyc:
  endpoint:
    uri: http://localhost:8080/api/verify
