spring.application.name=griisa-account-service
spring.datasource.hikari.maximum-pool-size=50
logging.level.org.springframework=INFO


# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/accountdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Batch DataSource uses the same config
spring.batch.initialize-schema=always
spring.batch.jdbc.url=${spring.datasource.url}
spring.batch.jdbc.username=${spring.datasource.username}
spring.batch.jdbc.password=${spring.datasource.password}
spring.batch.jdbc.driver-class-name=${spring.datasource.driver-class-name}

